admin/update-from-cc-for-dependabot-fix
OpenMontana/montana-legislature-council-data-project pull request #3
Opened 2022-09-08 17:56 UTC by evamaxfield

The same PR as the missoula one. Updates to cookiecutter to resolve the dependabot stuff.

Merge whenever and the current dependabot PRs should go away / be closeable regardless.

2023-01-05 03:48 UTC, whargrove requested changes
@evamaxfield Sorry it has taken a while to review this and thanks of course for the fix. IIUC the merge conflicts are caused by subsequent version bumps of cdp-backend we've applied, I've suggested some fixes here so that it can be merged.

Are you able to take a pass and make sure the merges resolve cleanly with the version of cdp-backned we need currently?

2023-01-05 03:48 UTC, whargrove commented on infra/requirements.txt
> +cdp-backend==3.2.3
```suggestion
cdp-backend==3.2.11
```

2023-01-05 03:48 UTC, whargrove commented on python/setup.py
> +    "cdp-backend[pipeline]==3.2.3",
```suggestion
    "cdp-backend[pipeline]==3.2.11",
```

2023-01-05 18:42 UTC, evamaxfield commented on cookiecutter.yaml
> +    event_gather_timedelta_lookback_days: 2
```suggestion
    event_gather_timedelta_lookback_days: 10
```

@whargrove for your tracking. smai had updated this in the app prior to the base app actually tracking it in the default build: https://github.com/OpenMontana/montana-legislature-council-data-project/blob/main/python/event-gather-config.json#L7

2023-01-05 18:43 UTC, evamaxfield reviewed
I think this is good again. Feel free to merge. Worst case is that you just need to rerun the cookiecutter

2023-01-06 00:29 UTC, whargrove approved these changes

2023-01-06 00:34 UTC, merged